début gabarit de base
heartbeatcountry/astro pull request #12
Opened 2023-09-20 19:18 UTC by sissifortier

2023-09-26 12:34 UTC, vermarine commented on src/styles/style.scss
> +	font-family:Georgia, 'Times New Roman', Times, serif;
On ne veut normalement jamais coder une police "à la dur" en Bootstrap. Si on souhaite changer la police, il faut redéfinir les variables css suivantes:

```css
  --bs-font-sans-serif: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  --bs-font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  --bs-body-font-family: var(--bs-font-sans-serif);
```

2023-09-26 12:36 UTC, vermarine commented on src/styles/style.scss
> +	text-align: center;
Je ne crois pas que 100% des en-têtes doivent être centrés. Aussi, il ne fait pas vraiment de sens de centrer les paragraphes ou les liens. Il serait préférable d'utiliser la classe `text-center` là ou nécessaire

2023-09-26 12:38 UTC, vermarine commented on src/styles/style.scss
> +	margin-top: 20px;
en bootstrap, on ne code jamais de taille à la dur:

```css
h1 {
    @extend .mt-3;
}
```

2023-09-26 12:38 UTC, vermarine commented on src/styles/style.scss
> +	background-image: url(../../images/background_header.png);
il manque des guillemets à l'intérieur du `url()`

2023-09-26 12:41 UTC, vermarine commented on src/styles/style.scss
> +	background-size: 100%;
Il est préférable d'utiliser `background-size: cover;`: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

Aussi, il cet arrière-plan devrait être dans le body plutôt que dans le header puisqu'il s'applique aussi au corps de la page. **La page ne devrait PAS se trouver dans le header**

2023-09-26 12:42 UTC, vermarine commented on src/styles/style.scss
> +	min-height:450px;
Il faut utiliser grid layout pour les dimensions; jamais de valeurs en pixels

2023-09-26 12:44 UTC, vermarine commented on src/styles/style.scss
> +	box-shadow: 300px 3000px 0 0 rgba(245, 249, 245, 0.704) inset;
Ici, le box-shadow est utilisé comme arrière-plan translucide. Il faudrait plutôt utiliser un rgba() avec transparence directement en tant que background-color

2023-09-26 12:44 UTC, vermarine commented on src/styles/style.scss
> +	background-color: rgba(0, 0, 0, 0.795);
Il faut utiliser les couleurs du thème bootswatch

2023-09-26 12:45 UTC, vermarine commented on src/styles/style.scss
> +	text-align: center;
`@extend .text-center`

2023-09-26 12:45 UTC, vermarine commented on src/styles/style.scss
> +	font-size: 1.5rem;
`@extend .fs-4`

2023-09-26 12:46 UTC, vermarine commented on src/styles/style.scss
> +		padding:10px;
`@extend .p-1`

2023-09-26 12:46 UTC, vermarine commented on src/styles/style.scss
> +	display: block;
`@extend .d-block`

2023-09-26 12:54 UTC, vermarine commented on src/styles/style.scss
> +@media screen and (max-width:1340px) {
il ne devrait jamais y avoir de media queries en bootstrap: il faut utiliser le grid layout

2023-09-27 18:06 UTC, vermarine approved these changes

2023-09-27 18:17 UTC, vermarine requested changes

2023-09-27 18:17 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +							<a href="index.html">Accueil</a>
les liens ne seront pas des vers des fichiers HTML, alors il serait préférable de changer les chemins pour les suivants:

```mermaid
flowchart LR
    index.html --> /
    services.html --> /services
    danses.html --> /danses
    evenements.html --> /evenements
    a_propos.html --> /a-propos
    deconnexion.html --> /compte/deconnexion
    connexion.html --> /compte/connexion
```

2023-09-27 18:17 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +				<a href="https://www.facebook.com/profile.php?id=100063673747492" target="_blank"><img class="mini"
Les `target="_blank"` sont une [mauvaise pratique](https://www.searchenginejournal.com/blank-link-attribute/435883/). Il vaut mieux laisser le visiteur ouvrir lui-même dans un nouvel onglet s'il le souhaite. De plus, tous les liens vers des sites externes devraient avoir un attribut `rel="noopener"`

2023-09-28 00:06 UTC, sissifortier commented on src/layouts/GabaritPrincipal.astro
> +							<a href="index.html">Accueil</a>
Ok, fait.  Pour le "a-propos", c'est vraiment un trait d'union?

2023-09-28 00:15 UTC, sissifortier commented on src/layouts/GabaritPrincipal.astro
> +				<a href="https://www.facebook.com/profile.php?id=100063673747492" target="_blank"><img class="mini"
Ok fait

2023-09-28 11:09 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +							<a href="index.html">Accueil</a>
c'est libre au choix; j'ai tout simplement soumis une suggestion 🙂

2023-09-28 11:12 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +				<a class="navbar-brand" href="index.html">
Pardon, j'ai oblié ce lien; il devrait aussi être `/`

2023-09-28 11:12 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +				<a href="index.html"><img  class="logo" src="images/logoblanctransparent.png"
Je ne comprends pas trop pourquoi on a un lien vers l'accueil dans le footer, mais, si c'est intentionnel, il faudrait changer son href 😉

2023-09-28 12:44 UTC, vermarine commented on src/layouts/GabaritPrincipal.astro
> +						src="images/icones/iconeFacebook2.png" alt="Logo Facebook" /></a>
idem pour les 4 icônes de médias sociaux

2023-09-28 19:35 UTC, vermarine approved these changes

2023-09-28 19:36 UTC, merged